### PR TITLE
Snapshot metadata and overlay WIP

### PR DESCRIPTION
**Pull request by Shadowen**
Addresses #136.

Records various metadata into a file at snapshot-time and uses it to add an overlay to the images before rendering. Also major rework of rendering flow using exceptions.

### CODE REVIEW

**Comment by Shadowen** [comment]
I haven't gone through and added settings to allow you to customize overlay font, size, location, colour, etc. yet. This will have to be done before merging.

**Comment by FormerLurker** [comment]
No problem, I'll wait until you're finished and the conflict is resolved to merge.  Let me know if I can help with the settings.  I know they are pretty nasty right now.

**Comment by Shadowen** [comment]
Alright, give this a shot. If you test on Windows, I'd appreciate it if you checked if the fonts in the settings menu load/work properly under Windows.

**Comment by FormerLurker** [comment]
Merged.  I'll pull now and check it out.  So exciting!

**Comment by FormerLurker** [comment]
No luck with the upgrade.  I'm searching for some solutions, but most I've found require 3rd party libraries that don't seem to be very cross platform friendly.  Will figure something out.

**Comment by FormerLurker** [comment]
It might be easier just to write a routine to search for fonts.  It's pretty easy in windows, but it also has to work for linux at least, hopefully mac too (though I don't own a mac to test).  Here is a file that from matplotlib that has a working function:

https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/font_manager.py

The function is called findSystemFonts.

I haven't read their license 100% either, so I'm not sure if we can use or derive from what's there.  However, it does contain the search paths for each OS, which is pretty useful.

I can't do much more today, but I'll try to get back on this tomorrow.  PIP has been a real pain in the butt for me.  Most libraries I have looked at fail to install due to missing requirements, which can't be installed themselves with PIP.  I wish I had more experience with this sort of thing, but I'm learning!

**Comment by Shadowen** [comment]
Huh, I didnt do anything on my end to install... I just relied on Octoprint to install through pip.

I did check out matplotlib's method, but it relies on searching certain directories configured in the matplotlibrc... I guess I could just hardcore a bunch of directories to search, but apparently under Linux you're supposed to reach a fonts.conf file. I'd rather use a library than parse a file :/

I'll see if I can replicate the pip issue. I am running an updated version of pip; perhaps that will help?

**Comment by FormerLurker** [comment]
Maybe my pup is out of date.  Will check on that either later today or tomorrow at the latest.

**Comment by Shadowen** [comment]
Doesn't seem to be a pip issue. As far as I can tell, the key library for fontconfig was `libfontconfig1-dev` in apt. Definitely didn't have to do anything from the original OctoPi image to get it to install though... Not sure how you install stuff on Windows though ;)

**Comment by Shadowen** [comment]
Looks like I misread the `fontconfig` page and it's only intended for Linux-like systems... I guess I'll just hack together some directory-searching algorithm that vaguely works on all systems?

**Pull request merged**
