### PR TITLE
Add printer profile for Lulzbot Taz 6.

### PR DESCRIPTION
**Pull request by bluecamel**
This is a fun diff :)

Here's prettified JSON for just the new printer profile:
```
{
    "movement_speed": 6000,
    "guid": "c75d2855-61c4-4aad-8aa7-bf03ac0da632",
    "min_x": -20.0,
    "min_y": -9.0,
    "min_z": 0.0,
    "detract_speed": 3000,
    "z_hop": 0.5,
    "max_z": 250.0,
    "max_x": 289.0,
    "max_y": 289.0,
    "description": "",
    "e_axis_default_mode": "require-explicit",
    "g90_influences_extruder": "use-octoprint-settings",
    "origin_z": 10.0,
    "origin_y": 10.0,
    "origin_x": 20.0,
    "priming_height": 0.0,
    "abort_out_of_bounds": false,
    "retract_speed": 4000,
    "auto_position_detection_commands": "",
    "name": "Lulzbot Taz 6",
    "retract_length": 2.0,
    "snapshot_command": "snap",
    "override_octoprint_print_volume": true,
    "z_hop_speed": 6000,
    "printer_position_confirmation_tolerance": 0.01,
    "units_default": "millimeters",
    "xyz_axes_default_mode": "require-explicit",
    "auto_detect_position": true
}
```

### CODE REVIEW

**Comment by bluecamel** [comment]
One other thing that was odd setting this printer up is the GCODE parsing.  I didn't dig deep in that code yet, but I can later and get a PR ready.  Anyhow, the Lulzbot version of Cura (I'm running the latest, 2.6.69), has default start GCODE that includes a homing command of `G28 XY`.  To make things work, I changed this to `G28 X Y` and it parses it and seems to determines location correctly.

I should say that I haven't tested this extensively, but I've done a couple of prints and it's been working.  Still tweaking and learning!  BTW, thanks for this awesome project ❤️

**Comment by bluecamel** [comment]
And yet another note.  I'm not entirely confident that this was the right thing to do here, but the Taz 6 has leveling probes at each corner of the build plate, as well as a nozzle wiping pad at the front left.  The real build volume is 280 X, 280 Y, 250 Z, but that kept throwing Octolapse off when it would go to X 289 or X -19 for the leveling and cleaning process.  So, I just had Octolapse override the volume to include this full range and it seems happy.

**Comment by FormerLurker** [comment]
I'm glad you like it, and thanks for the profile!  Can you redo the pull request and target the devel branch instead?  I've been making some changes, and I MAY have altered the settings somewhat.  I could also just copy/paste it in if you would rather not bother.  Let me know, and THANKS for the profile!

Yeah, there are definitely some parsing issues.  Currently it only works with GCode that I've seen so far, or stuff that's defined on the reprap gcode wiki.  I am writing a brand new parser that should be more compliant (space agnostic, inline comments, etc).  I wish I understood gcode better when I first wrote the parser, lol.  I've only had a printer for a little over a year and am sort of learning as I go.

Yes, include this extra area in the print profile.  As a safety precaution, Octolapse will throw a position error if it believes the print head is in an out-of-bounds position.  This also affects the 'bed relative' coordinates in the 'stabilization' profiles.  If your volume isn't correct, you can have problems with relative positions along the edge of the printer.

**Comment by FormerLurker** [comment]
Hey, I ended up just copying that json in, which was easier than dealing with this PR, I hope you don't mind.  I could have sworn I sent a comment after my commit yesterday, but apparently not.  I also formatted the .json file to make this easier in the future.  I'm not sure why I haven't already done that!

Thanks again!

**Pull request closed without merging**
