### PR TITLE
Circular buffer using deque. Also fixed relevant tests.

### PR DESCRIPTION
**Pull request by Shadowen**
#25

### CODE REVIEW

**Comment by FormerLurker** [comment]
I decided to leave the W alone.  I'm not sure why Prusa has it in their start code, but it always appears this way:

G28 W
G80

G80 is used for mesh bed leveling on the MK2/3 apparently.  Perhaps this is used because the origin can change slightly after running G80?  However, if we require that W is missing in order to home the other 3 axis, G80 MUST be in the list of additional commands that require position detection, else Octolapse won't think it's been homed properly.

I'll do some testing on this tomorrow.

**Comment by Shadowen** [comment]
I use Slic3r (Prusa Edition). Are you talking about Prusa Control
generating this GCode? I haven't seen that particular line (though I don't
look at GCode a lot...).

**Comment by FormerLurker** [comment]
Yeah, slicer prusa edition.  It's in the default start GCode for the multi material upgrade (not sure about mk2s or mk3 yet, but I will check).

I'll post on their forum or will email them and ask what it does.

**Comment by FormerLurker** [comment]
Yeah, slicer prusa edition.  It's in the default start GCode for the multi material upgrade (not sure about mk2s or mk3 yet, but I will check).

I'll post on their forum or will email them and ask what it does.

**Comment by FormerLurker** [comment]
I've discovered that G28 W performs a home WITHOUT mesh bed leveling.  G28 alone will do the mesh bed leveling too.

So this:

G28

is equivalent to this:

G28 W
G80

It looks like leaving the W param off of that check is the right call.  It's already been removed from BetaDevelopment.

I'm still not sure if this:

G28 W
G80

is equivalent to this: 

G28 W
G29....

**Comment by Shadowen** [comment]
Okay, it's just that there was a test needs to be fixed in that case.

**Comment by FormerLurker** [comment]
I'll add that.  I plan to work on the final tests tonight.  Thanks again
for all of your hard work thus far!

**Pull request merged**
