### PR TITLE
More formatting, sorry for any messy commits

### PR DESCRIPTION
**Pull request by ppessi**

### CODE REVIEW

**Comment by FormerLurker** [comment]
Hot diggity!  I'll review asap.  Got 1 commit to push beforehand.

Thanks again!

**Comment by FormerLurker** [comment]
Ok, I pushed my changes and resolved the conflicts.  The commit wasn't too messy!  I like your changes to settings.py, and especially command.py.

I'll have to get used to the shorter lines.  I've got a nice big 4k screen, and half of my editor is empty now, lol!  It's still a good trade for consistency.  However, I'm still having trouble getting my editor to obey the line length restrictions.  It wraps them appropriately, but doesn't actually insert the break/spaces.  Which leads me to the next question:

A.  Do you prefer YAPF or autopep8?
B.  Should I run one of these automatically before commit (or is there a better way)?  That might help keep things clean going forward.

Let me know what you think, and thanks again for the beautification!  I'm going to merge right now.

**Comment by ppessi** [comment]
I've never used autopep8 before, only used for this project. Haven't heard of YAPF. I guess running autopep8 before committing would be good, but it would be better if you just formatted all code properly as you write it. I personally don't use any automatic formatting.

**Comment by FormerLurker** [comment]
Coding it correctly the first time is certainly best, but it's going to take me a while to get into the swing of things.  I use re-sharper and other tools for work a lot, and it makes it pretty much impossible to make a mistake, so I'm pretty spoiled.  I'm starting to understand why things are the way they are, and slowly learning.  I have to read that style guide about 100 more times and make about 1000 more mistakes before I remember everything.

YAPF apparently makes things more consistent than autopep8 (it changes code that technically meets the spec to standard formats, while autopep8 leaves things alone if they meet the spec, or so I've heard).  I figure I won't be the only one having trouble adhering to the standard at first.  I'd also like to avoid as many styling arguments as possible when dealing with pull requests.

Please free to point out any mistakes I make regarding the styling if you come across something you fixed that I broke.  If you have the time, I'd love some reinforcement!  Thanks again!

**Comment by FormerLurker** [comment]
Thought you'd like to know about 95% of .py files have been refactored and reformatted.  If you have some time, let me know what you think.  

I just gutted timelapse.py (NoPause branch, exciting stuff), so a few things need removal/tweaking.  There are still long lines, but I'm having a really hard time with the narrow width.  I'm breaking now at 120 char, which is still less than half of the width of my window :)

**Comment by ppessi** [comment]
Looks pretty good. :) Some things could still be fixed though, I'm not sure if they're mentioned in pep8 but would possibly look better:
If you have to put function input on multiple lines it would look better if the indentation on the next line would be 4 spaces instead of starting at the parenthesis, for example line 183-185 in extruder.py:
```
self.Settings.current_debug_profile().log_warning("extruder.py - A 'length_to_retract' was requested, "
                                                  "but the extruder is beyond the configured retraction "
                                                  "length.")
```
vs (I also made the line length more even, so the "length" wasn't lonely anymore, looks better)
```
self.Settings.current_debug_profile().log_warning(
    "extruder.py - A 'length_to_retract' was requested, but "
    "the extruder is beyond the configured retraction length.")
```
Personally I also find it easier to read code if in cases like this the closing parenthesis is on the same level as the function, like this:
```
self.Settings.current_debug_profile().log_warning(
    "extruder.py - A 'length_to_retract' was requested, but "
    "the extruder is beyond the configured retraction length."
)
```
But I'm not sure there's a general guideline, its just my personal preference.

I'm not sure if you've decided to do it like this for the sake of more easily understanding the code or if you're just unfamiliar with Python, but its not necessary to write True and False in these:
`state.IsExtruding = True if state.ExtrusionLength > 0 else False`
You can also do this, since `state.ExtrusionLength > 0` and any other comparison is a boolean:
`state.IsExtruding = state.ExtrusionLength > 0`

Not sure if its still true but at some point you had both comments written with """ and comments written with #, it would probably be better to select one style. Or you could use # for single-line comments and """ for multiline comments.

**Comment by FormerLurker** [comment]
> I'm not sure if you've decided to do it like this for the sake of more easily understanding the code or if you're just unfamiliar with Python, but its not necessary to write True and False in these:
> state.IsExtruding = True if state.ExtrusionLength > 0 else False

Good catch.  I believe I had quite a different logical operation there in the recent past (i think it was possible for extrusion length to be None at one point), and did not rewrite it.  That is no doubt the case in other areas.  You are also correct that I'm unfamiliar with python, but I'm learning with some help!

> Personally I also find it easier to read code if in cases like this the closing parenthesis is on the same level as the function

I've been going back and forth on this.  Pycharm seems to want to indent it to the first '(' when using the 'fill paragraph' formatting option, but I prefer the 4 space indent as you have.  I'll look into reconfiguring autoformat.  Not sure about the final ')'.  I've been going back and forth (which is the worst thing you can do, right).  Since I'm wavering I'll try the second option (end parenthesis on same indent)

I also did a bit of work on the member naming conventions, but they are still somewhat inconsistent.  I am thinking I need to prefix 'private' functions with __.  Also, in some cases my members are camel case and sometimes they are not (I prefer camel myself).

Thanks for your suggestions!

**Pull request merged**
